apiVersion: v1
kind: Service
metadata:
  name: scurvy-bot-service
spec:
  selector:
    app: scurvy-bot
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scurvy-bot
  labels:
    app: scurvy-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scurvy-bot
  template:
    metadata:
      labels:
        app: scurvy-bot
    spec:
      containers:
      - name: scurvy-bot-app
        image: gcr.io/grubstavern/scurvy-bot:latest
        env:
          - name: SCURVY_DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: scurvy-token
                key: discord
