apiVersion: apps/v1
kind: Deployment
metadata:
  name: scurvy-bot-worker
  labels:
    app: scurvy-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scurvy-bot
  template:
    metadata:
      labels:
        app: scurvy-bot
    spec:
      containers:
      - name: scurvy-bot-app
        image: gcr.io/grubstavern/scurvy-bot:latest
        env:
          - name: SCURVY_DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: scurvy-token
                key: discord
